Add DTV map Musa Point
namidaka/crpg pull request #247
Opened 2024-01-06 12:53 UTC by rf-l

New DTV map Musa Point

2024-01-09 15:02 UTC, namidaka requested changes

2024-01-09 15:02 UTC, namidaka commented on src/Module.Client/GUI/MapSpriteData.xml
>        <AlwaysLoad />
where's 137?

2024-01-09 15:13 UTC, namidaka commented on src/Module.Client/GUI/MapSpriteData.xml
>        <AlwaysLoad />
Volskullkeep has been merged , conflicts needs to be handled

2024-01-13 12:26 UTC, namidaka approved these changes

2024-01-19 20:52 UTC, rf-l commented
Another commit for new map (Temple of Poseidon). Thought it would open a new PR. Since I thought it was merged.

2024-01-20 18:28 UTC, namidaka commented
> Another commit for new map (Temple of Poseidon). Thought it would open a new PR. Since I thought it was merged.

![image](https://github.com/namidaka/crpg/assets/47090987/17646a6c-1fb7-4e87-8376-7684e848753a)
This has never been properly rebased

2024-01-20 18:54 UTC, rf-l commented
Ah, hope this fixed it.

2024-01-20 20:22 UTC, merged