DTV clan round of Grey Order
namidaka/crpg pull request #276
Opened 2024-02-03 00:01 UTC by CapitalBerserkTamra

Talked with Droob about adding my own DTV round of the very old clan in cRPG1 The Grey Order.
The bots represent the playstyle used by GO the most, like Agility-focused shielders and Two-Handed users as well as very heavy Tincan builds - I didn't add ranged nor cavalry, I'd like to see how players fare against a late-map (after dwarves) melee only round which shifts from agility bots to strength bots.

2 lieutenants/bosses per wave named after very known Grey Order members.

Open to feedback and there might be errors in the code still.

2024-02-03 16:42 UTC, Norr2 commented on src/Module.Server/ModuleData/dtv/dtv_characters.xml
> +        <equipment slot="Leg" id="Item.crpg_plated_strip_boots_v2_h0"" />
There is an extra " on line:
3413

2024-02-03 16:46 UTC, Norr2 commented on src/Module.Server/ModuleData/dtv/dtv_characters.xml
> +        <equipment slot="Leg" id="Item.crpg_plated_strip_boots_v2_h0"" />
There is an extra " on line:
3413
3546
3585
3624
3664
3703
Almost all the lines with boots

2024-02-03 17:35 UTC, Norr2 commented on src/Module.Server/ModuleData/dtv/dtv_characters.xml
> +        <equipment slot="Leg" id="Item.crpg_plated_strip_boots_v2_h0"" />
You missed lin 3546 :)

2024-02-03 18:01 UTC, namidaka commented
> Talked with Droob about adding my own DTV round of the very old clan in cRPG1 The Grey Order.
> 
> The bots represent the playstyle used by GO the most, like Agility-focused shielders and Two-Handed users as well as very heavy Tincan builds - I didn't add ranged nor cavalry, I'd like to see how players fare against a late-map (after dwarves) melee only round which shifts from agility bots to strength bots.
> 
> 2 lieutenants/bosses per wave named after very known Grey Order members.
> 
> Open to feedback and there might be errors in the code still.
> 
> Implementing a round like this might motivate other players/clans to do similar.

This is indeed a good addition. I'll wait for droob to evaluate how hard the wave in order to estimate where to slot it in , as i have no specific knowledge of dtv waves.

2024-02-03 18:08 UTC, Norr2 approved these changes
Changes done

2024-02-03 20:06 UTC, CapitalBerserkTamra commented
Tested it with Norr, it only crashed 3 times until it started working :)

2024-02-04 22:25 UTC, Norr2 commented on src/Module.Server/ModuleData/dtv/dtv_class_divisions.xml
> +    <MPClassDivision id="ccrpg_dtv_greyorder_balanced_infantry"
Just noticed line 1922 here has "ccrpg..."

2024-02-11 09:59 UTC, Muparadzi commented
@namidaka what are your thoughts on having bot names as direct references to players? On some other rounds we have slightly more obscure references such as Duke Rafael (rfl) and Droobert Humperdink. I'm thinking maybe we should follow suite with this round.

2024-02-11 12:06 UTC, CapitalBerserkTamra commented
Just my thoughts:
In my opinion not allowing real player names would kind of remove the whole idea of having clan-specific rounds.

If people put in the work to have their clan represented in the DTV game mode while improving it; why not giving them that small goodie of having actual real player names represented.

I dunno if I could come up with meaningful synonyms.
Might just change the other bot names of rfl and co. in my opinion if that's an issue.

2024-02-13 16:50 UTC, Muparadzi requested changes
Thanks for the submission, I think they are in a good place difficulty wise with some slight changes.

2024-02-13 16:50 UTC, Muparadzi commented on src/Module.Server/ModuleData/dtv/dtv_data.xml
> +	  <Group classDivisionId="crpg_dtv_greyorder_boss_hetman" />
There are some inconsistencies with your tabs here

2024-02-13 16:50 UTC, Muparadzi commented on src/Module.Server/ModuleData/dtv/dtv_class_divisions.xml
> +                   melee_ai="70"
I would bring the `melee_ai` down for all of your regular units. Tincans & dwarves have only 30 in comparison to your 70. Maybe make them 50 so they are still formidable in melee to account for the lack of ranged units.

2024-03-03 11:39 UTC, Muparadzi submitted a review, later dismissed

2024-03-03 11:39 UTC, Muparadzi approved these changes

2024-03-09 16:34 UTC, merged