feat: seperate statistics by gamemode
namidaka/crpg pull request #323
Opened 2024-03-17 18:14 UTC by Muparadzi

Changes Character.Statistics to `IList<CharacterStatistics>` and adds `GameMode` enum property to `CharacterStatistics`.

![306793551-69c37d55-4afa-4717-886d-9536cb274e1b](https://github.com/namidaka/crpg/assets/93069911/18a0b343-85ae-41bd-bcda-721dd721a179)

rebase nightmare from #288

2024-03-17 23:41 UTC, or2e commented on src/Domain/Entities/Characters/CharacterStatistics.cs
>  }
You need to add a navigation property:
`public Character? Character{ get; set; }`


After that, you need to delete the old migration and create a new migration

ref1:
```
src/Domain/Entities/Parties/PartyItem.cs
```
ref2: https://learn.microsoft.com/en-us/ef/ef6/fundamentals/relationships

2024-03-31 13:20 UTC, namidaka requested changes

2024-03-31 13:20 UTC, namidaka commented on src/Persistence/Migrations/20240318115855_AddGamemodeStatistics.cs
> +    }
warnings

2024-03-31 15:17 UTC, or2e approved these changes

2024-06-04 09:05 UTC, or2e approved these changes

2024-06-04 10:04 UTC, merged