moved tickspersecond in damagezone.cs to public editor variable
namidaka/crpg pull request #353
Opened 2024-05-11 13:35 UTC by rau98

2024-05-14 12:58 UTC, Meowkov submitted a review, later dismissed
Looking good.

2024-05-14 16:00 UTC, Muparadzi requested changes

2024-05-14 16:00 UTC, Muparadzi commented on src/Module.Server/Scripts/DamageZone.cs
> +    //private const int TicksPerSecond = 2;
you can remove this line

2024-05-22 08:32 UTC, Muparadzi approved these changes
Thanks for your first PR!

2024-05-28 19:20 UTC, Meowkov approved these changes
Approved

2024-07-05 21:15 UTC, or2e approved these changes

2024-07-06 03:34 UTC, Yeldur approved these changes
approved

2024-07-08 08:09 UTC, merged