mod: change the battle flag system to warband style
namidaka/crpg pull request #94
Opened 2023-10-14 03:54 UTC by MrMendo

Also seperated the skirmish flag system from battle flag system

2023-10-15 21:03 UTC, namidaka requested changes

2023-10-15 21:25 UTC, namidaka requested changes

2023-10-15 21:25 UTC, namidaka commented on src/Module.Server/Modes/Battle/FlagSystems/CrpgBattleFlagSystem.cs
> +        SetWereFlagsManipulated(true);
Consider WereFlagsManipulated -> HasFlagCountChanged

2023-10-15 22:18 UTC, namidaka requested changes

2023-10-15 22:18 UTC, namidaka commented on src/Module.Server/Modes/Battle/FlagSystems/CrpgBattleFlagSystem.cs
> +        float currentSpawnedPlayerCount = GetCurrentSpawnedPlayerCount();
spawned -> alive

2023-10-15 22:23 UTC, namidaka requested changes

2023-10-15 22:23 UTC, namidaka commented on src/Module.Server/Modes/Battle/CrpgBattleServer.cs
>              }
Check can be removed, because 
Math.Abs(_morale) >= 1.0 && !_flagSystem.WereFlagsManipulated() is always equal to false

2023-10-15 22:44 UTC, namidaka requested changes

2023-10-15 22:44 UTC, namidaka commented on src/Module.Server/Modes/Battle/FlagSystems/CrpgBattleFlagSystem.cs
> +    }
to remove

2023-10-15 22:44 UTC, namidaka commented on src/Module.Server/Modes/Battle/FlagSystems/CrpgBattleFlagSystem.cs
> +    }
public void CheckForDeadPlayerFlagSpawnThreshold()
    {
        int attackerCount = Mission.AttackerTeam.ActiveAgents.Count;
        int defenderCount = Mission.DefenderTeam.ActiveAgents.Count;
        // Todo : To move to server configuration
        float overpowerTheshold = 2f;
        if (attackerCount == 1 || defenderCount == 1)
        {
            // spawn flag
        }

        if (attackerCount > 7 || defenderCount > 7)
        {
            return;
        }

        if (Crpg.Module.Helpers.MathHelper.Within((float)attackerCount / (float)defenderCount, 1 / overpowerTheshold, overpowerTheshold))
        {
            return;
        }

        // spawn flag
    }

2023-10-15 22:47 UTC, MrMendo commented on src/Module.Server/Modes/Battle/CrpgBattleClient.cs
> +                registerer.Register<CrpgBattleSpawnFlagMessage>(OnFlagsRemovedBattle);
Done

2023-10-15 22:47 UTC, MrMendo commented on src/Module.Server/Modes/Battle/CrpgBattleClient.cs
> +    private void OnFlagsRemovedBattle(CrpgBattleSpawnFlagMessage message)
Done

2023-10-15 22:53 UTC, namidaka requested changes

2023-10-15 22:53 UTC, namidaka commented on src/Module.Server/Modes/Battle/FlagSystems/CrpgBattleFlagSystem.cs
> +    protected override bool IsAgentCountingAroundFlag(Agent agent) => !agent.IsActive() || !agent.IsHuman || agent.HasMount;
CanAgentCaptureFlag

2023-10-16 13:49 UTC, namidaka approved these changes

2023-10-16 13:49 UTC, merged